/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.ecoretools.ale.impl;

import java.util.Collection;

import org.eclipse.ecoretools.ale.AlePackage;
import org.eclipse.ecoretools.ale.Expr;
import org.eclipse.ecoretools.ale.expressionSequence;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>expression Sequence</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.ecoretools.ale.impl.expressionSequenceImpl#getSeqExprs <em>Seq Exprs</em>}</li>
 * </ul>
 *
 * @generated
 */
public class expressionSequenceImpl extends ClassExpImpl implements expressionSequence
{
  /**
   * The cached value of the '{@link #getSeqExprs() <em>Seq Exprs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeqExprs()
   * @generated
   * @ordered
   */
  protected EList<Expr> seqExprs;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected expressionSequenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AlePackage.Literals.EXPRESSION_SEQUENCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Expr> getSeqExprs()
  {
    if (seqExprs == null)
    {
      seqExprs = new EObjectContainmentEList<Expr>(Expr.class, this, AlePackage.EXPRESSION_SEQUENCE__SEQ_EXPRS);
    }
    return seqExprs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AlePackage.EXPRESSION_SEQUENCE__SEQ_EXPRS:
        return ((InternalEList<?>)getSeqExprs()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AlePackage.EXPRESSION_SEQUENCE__SEQ_EXPRS:
        return getSeqExprs();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AlePackage.EXPRESSION_SEQUENCE__SEQ_EXPRS:
        getSeqExprs().clear();
        getSeqExprs().addAll((Collection<? extends Expr>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AlePackage.EXPRESSION_SEQUENCE__SEQ_EXPRS:
        getSeqExprs().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AlePackage.EXPRESSION_SEQUENCE__SEQ_EXPRS:
        return seqExprs != null && !seqExprs.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //expressionSequenceImpl
