/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.ecoretools.ale;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>rOpen Class</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.emf.ecoretools.ale.AlePackage#getrOpenClass()
 * @model
 * @generated
 */
public interface rOpenClass extends rClass
{
} // rOpenClass
