/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.RStatement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>RStatement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RStatementImpl extends MinimalEObjectImpl.Container implements RStatement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.RSTATEMENT;
  }

} //RStatementImpl
