/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.ecoretools

import org.eclipse.xtext.formatting2.IFormatter2
import org.eclipse.emf.ecoretools.formatting2.AleFormatter

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class AleRuntimeModule extends AbstractAleRuntimeModule {
		
	override Class<? extends IFormatter2> bindIFormatter2() {
		AleFormatter
	}
	
}
