grammar fr.inria.diverse.XtdAQL with org.eclipse.xtext.xbase.Xbase

generate xtdAQL "http://www.inria.fr/diverse/XtdAQL"

//import "http://www.eclipse.org/emf/2002/Ecore" as ecore

Root : 
	(classes+=Class)*
;

Class : 'class' name=ID '{'
		(methods+=Method)*
	'}'
;

Method : 'def' name=ID '(' (param+=Parameter)* ')' '{'
	body=QRY
	'}'
;

Parameter : type=JvmTypeReference name=ID
;

terminal QRY	: '[' -> '/]';
