/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.ecoretools.ale;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.eclipse.ecoretools.ale.AleFactory
 * @model kind="package"
 * @generated
 */
public interface AlePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "ale";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.eclipse.org/ecoretools/Ale";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "ale";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AlePackage eINSTANCE = org.eclipse.ecoretools.ale.impl.AlePackageImpl.init();

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.RRootImpl <em>RRoot</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.RRootImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRRoot()
   * @generated
   */
  int RROOT = 0;

  /**
   * The feature id for the '<em><b>Xtended Classes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RROOT__XTENDED_CLASSES = 0;

  /**
   * The number of structural features of the '<em>RRoot</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RROOT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.RClassImpl <em>RClass</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.RClassImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRClass()
   * @generated
   */
  int RCLASS = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RCLASS__NAME = 0;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RCLASS__ATTRIBUTES = 1;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RCLASS__OPERATIONS = 2;

  /**
   * The number of structural features of the '<em>RClass</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RCLASS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.ROpenClassImpl <em>ROpen Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.ROpenClassImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getROpenClass()
   * @generated
   */
  int ROPEN_CLASS = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROPEN_CLASS__NAME = RCLASS__NAME;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROPEN_CLASS__ATTRIBUTES = RCLASS__ATTRIBUTES;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROPEN_CLASS__OPERATIONS = RCLASS__OPERATIONS;

  /**
   * The feature id for the '<em><b>Open Class</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROPEN_CLASS__OPEN_CLASS = RCLASS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>ROpen Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROPEN_CLASS_FEATURE_COUNT = RCLASS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.RNewClassImpl <em>RNew Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.RNewClassImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRNewClass()
   * @generated
   */
  int RNEW_CLASS = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RNEW_CLASS__NAME = RCLASS__NAME;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RNEW_CLASS__ATTRIBUTES = RCLASS__ATTRIBUTES;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RNEW_CLASS__OPERATIONS = RCLASS__OPERATIONS;

  /**
   * The feature id for the '<em><b>New Class</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RNEW_CLASS__NEW_CLASS = RCLASS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>RNew Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RNEW_CLASS_FEATURE_COUNT = RCLASS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.rOperationImpl <em>rOperation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.rOperationImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getrOperation()
   * @generated
   */
  int ROPERATION = 4;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROPERATION__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROPERATION__NAME = 1;

  /**
   * The feature id for the '<em><b>Param List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROPERATION__PARAM_LIST = 2;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROPERATION__BODY = 3;

  /**
   * The number of structural features of the '<em>rOperation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROPERATION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.rParametersImpl <em>rParameters</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.rParametersImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getrParameters()
   * @generated
   */
  int RPARAMETERS = 5;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RPARAMETERS__PARAMS = 0;

  /**
   * The number of structural features of the '<em>rParameters</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RPARAMETERS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.rVariableImpl <em>rVariable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.rVariableImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getrVariable()
   * @generated
   */
  int RVARIABLE = 6;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RVARIABLE__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RVARIABLE__NAME = 1;

  /**
   * The number of structural features of the '<em>rVariable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RVARIABLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.rAttributeImpl <em>rAttribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.rAttributeImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getrAttribute()
   * @generated
   */
  int RATTRIBUTE = 7;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RATTRIBUTE__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RATTRIBUTE__NAME = 1;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RATTRIBUTE__EXPR = 2;

  /**
   * The number of structural features of the '<em>rAttribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RATTRIBUTE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.RStatementImpl <em>RStatement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.RStatementImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRStatement()
   * @generated
   */
  int RSTATEMENT = 8;

  /**
   * The number of structural features of the '<em>RStatement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RSTATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.rVarDeclImpl <em>rVar Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.rVarDeclImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getrVarDecl()
   * @generated
   */
  int RVAR_DECL = 9;

  /**
   * The number of structural features of the '<em>rVar Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RVAR_DECL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.RAssignImpl <em>RAssign</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.RAssignImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRAssign()
   * @generated
   */
  int RASSIGN = 10;

  /**
   * The feature id for the '<em><b>Stmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RASSIGN__STMT = RSTATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RASSIGN__LEFT = RSTATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RASSIGN__RIGHT = RSTATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>RAssign</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RASSIGN_FEATURE_COUNT = RSTATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.RForEachImpl <em>RFor Each</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.RForEachImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRForEach()
   * @generated
   */
  int RFOR_EACH = 11;

  /**
   * The feature id for the '<em><b>For Each</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RFOR_EACH__FOR_EACH = RSTATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>RFor Each</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RFOR_EACH_FEATURE_COUNT = RSTATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.rCollectionImpl <em>rCollection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.rCollectionImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getrCollection()
   * @generated
   */
  int RCOLLECTION = 12;

  /**
   * The feature id for the '<em><b>For Each</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RCOLLECTION__FOR_EACH = RFOR_EACH__FOR_EACH;

  /**
   * The feature id for the '<em><b>Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RCOLLECTION__BLOCK = RFOR_EACH_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>rCollection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RCOLLECTION_FEATURE_COUNT = RFOR_EACH_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.rBlockImpl <em>rBlock</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.rBlockImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getrBlock()
   * @generated
   */
  int RBLOCK = 13;

  /**
   * The feature id for the '<em><b>Statement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RBLOCK__STATEMENT = 0;

  /**
   * The number of structural features of the '<em>rBlock</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RBLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.RIfImpl <em>RIf</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.RIfImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRIf()
   * @generated
   */
  int RIF = 14;

  /**
   * The feature id for the '<em><b>If</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIF__IF = RSTATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIF__CONDITION = RSTATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>If Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIF__IF_BLOCK = RSTATEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Else Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIF__ELSE_BLOCK = RSTATEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>RIf</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIF_FEATURE_COUNT = RSTATEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.RWhileImpl <em>RWhile</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.RWhileImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRWhile()
   * @generated
   */
  int RWHILE = 15;

  /**
   * The feature id for the '<em><b>While</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RWHILE__WHILE = RSTATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>RWhile</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RWHILE_FEATURE_COUNT = RSTATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.RExpressionImpl <em>RExpression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.RExpressionImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRExpression()
   * @generated
   */
  int REXPRESSION = 16;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REXPRESSION__EXPR = RSTATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>RExpression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REXPRESSION_FEATURE_COUNT = RSTATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.ExprImpl <em>Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.ExprImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getExpr()
   * @generated
   */
  int EXPR = 17;

  /**
   * The feature id for the '<em><b>For Each</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__FOR_EACH = RVAR_DECL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__BLOCK = RVAR_DECL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>While</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__WHILE = RVAR_DECL_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__EXPR = RVAR_DECL_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Rec Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__REC_EXP = RVAR_DECL_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__CONDITION = RVAR_DECL_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>If Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__IF_BLOCK = RVAR_DECL_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Else Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__ELSE_BLOCK = RVAR_DECL_FEATURE_COUNT + 7;

  /**
   * The feature id for the '<em><b>Bindings</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__BINDINGS = RVAR_DECL_FEATURE_COUNT + 8;

  /**
   * The feature id for the '<em><b>Let Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__LET_EXPR = RVAR_DECL_FEATURE_COUNT + 9;

  /**
   * The feature id for the '<em><b>Left Part</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__LEFT_PART = RVAR_DECL_FEATURE_COUNT + 10;

  /**
   * The feature id for the '<em><b>Recpart</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__RECPART = RVAR_DECL_FEATURE_COUNT + 11;

  /**
   * The number of structural features of the '<em>Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_FEATURE_COUNT = RVAR_DECL_FEATURE_COUNT + 12;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.RecExpressionImpl <em>Rec Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.RecExpressionImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRecExpression()
   * @generated
   */
  int REC_EXPRESSION = 18;

  /**
   * The feature id for the '<em><b>Rec Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REC_EXPRESSION__REC_EXP = 0;

  /**
   * The number of structural features of the '<em>Rec Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REC_EXPRESSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.NavigationSegmentImpl <em>Navigation Segment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.NavigationSegmentImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getNavigationSegment()
   * @generated
   */
  int NAVIGATION_SEGMENT = 19;

  /**
   * The feature id for the '<em><b>Rec Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAVIGATION_SEGMENT__REC_EXP = REC_EXPRESSION__REC_EXP;

  /**
   * The number of structural features of the '<em>Navigation Segment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAVIGATION_SEGMENT_FEATURE_COUNT = REC_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.nonLeftRecExpressionImpl <em>non Left Rec Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.nonLeftRecExpressionImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getnonLeftRecExpression()
   * @generated
   */
  int NON_LEFT_REC_EXPRESSION = 20;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NON_LEFT_REC_EXPRESSION__CONDITION = 0;

  /**
   * The feature id for the '<em><b>If Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NON_LEFT_REC_EXPRESSION__IF_BLOCK = 1;

  /**
   * The feature id for the '<em><b>Else Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NON_LEFT_REC_EXPRESSION__ELSE_BLOCK = 2;

  /**
   * The feature id for the '<em><b>Bindings</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NON_LEFT_REC_EXPRESSION__BINDINGS = 3;

  /**
   * The feature id for the '<em><b>Let Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NON_LEFT_REC_EXPRESSION__LET_EXPR = 4;

  /**
   * The number of structural features of the '<em>non Left Rec Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NON_LEFT_REC_EXPRESSION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.bindingImpl <em>binding</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.bindingImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getbinding()
   * @generated
   */
  int BINDING = 21;

  /**
   * The number of structural features of the '<em>binding</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDING_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.callExpImpl <em>call Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.callExpImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getcallExp()
   * @generated
   */
  int CALL_EXP = 22;

  /**
   * The number of structural features of the '<em>call Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALL_EXP_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.expressionSequenceImpl <em>expression Sequence</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.expressionSequenceImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getexpressionSequence()
   * @generated
   */
  int EXPRESSION_SEQUENCE = 23;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_SEQUENCE__CONDITION = CALL_EXP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>If Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_SEQUENCE__IF_BLOCK = CALL_EXP_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Else Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_SEQUENCE__ELSE_BLOCK = CALL_EXP_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Bindings</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_SEQUENCE__BINDINGS = CALL_EXP_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Let Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_SEQUENCE__LET_EXPR = CALL_EXP_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Seq Exprs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_SEQUENCE__SEQ_EXPRS = CALL_EXP_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>expression Sequence</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_SEQUENCE_FEATURE_COUNT = CALL_EXP_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.literalImpl <em>literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.literalImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getliteral()
   * @generated
   */
  int LITERAL = 24;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL__CONDITION = NON_LEFT_REC_EXPRESSION__CONDITION;

  /**
   * The feature id for the '<em><b>If Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL__IF_BLOCK = NON_LEFT_REC_EXPRESSION__IF_BLOCK;

  /**
   * The feature id for the '<em><b>Else Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL__ELSE_BLOCK = NON_LEFT_REC_EXPRESSION__ELSE_BLOCK;

  /**
   * The feature id for the '<em><b>Bindings</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL__BINDINGS = NON_LEFT_REC_EXPRESSION__BINDINGS;

  /**
   * The feature id for the '<em><b>Let Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL__LET_EXPR = NON_LEFT_REC_EXPRESSION__LET_EXPR;

  /**
   * The number of structural features of the '<em>literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL_FEATURE_COUNT = NON_LEFT_REC_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.RValDeclImpl <em>RVal Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.RValDeclImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRValDecl()
   * @generated
   */
  int RVAL_DECL = 25;

  /**
   * The feature id for the '<em><b>Stmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RVAL_DECL__STMT = RSTATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>RVal Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RVAL_DECL_FEATURE_COUNT = RSTATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.FinalIdentSegmentImpl <em>Final Ident Segment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.FinalIdentSegmentImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getFinalIdentSegment()
   * @generated
   */
  int FINAL_IDENT_SEGMENT = 26;

  /**
   * The feature id for the '<em><b>Rec Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINAL_IDENT_SEGMENT__REC_EXP = NAVIGATION_SEGMENT__REC_EXP;

  /**
   * The feature id for the '<em><b>Ident</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINAL_IDENT_SEGMENT__IDENT = NAVIGATION_SEGMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Final Ident Segment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINAL_IDENT_SEGMENT_FEATURE_COUNT = NAVIGATION_SEGMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.FinalIdentCallSegmentImpl <em>Final Ident Call Segment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.FinalIdentCallSegmentImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getFinalIdentCallSegment()
   * @generated
   */
  int FINAL_IDENT_CALL_SEGMENT = 27;

  /**
   * The feature id for the '<em><b>Rec Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINAL_IDENT_CALL_SEGMENT__REC_EXP = NAVIGATION_SEGMENT__REC_EXP;

  /**
   * The feature id for the '<em><b>Call</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINAL_IDENT_CALL_SEGMENT__CALL = NAVIGATION_SEGMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Final Ident Call Segment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINAL_IDENT_CALL_SEGMENT_FEATURE_COUNT = NAVIGATION_SEGMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.eclipse.ecoretools.ale.impl.FinalCallExpSegmentImpl <em>Final Call Exp Segment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.ecoretools.ale.impl.FinalCallExpSegmentImpl
   * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getFinalCallExpSegment()
   * @generated
   */
  int FINAL_CALL_EXP_SEGMENT = 28;

  /**
   * The feature id for the '<em><b>Rec Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINAL_CALL_EXP_SEGMENT__REC_EXP = NAVIGATION_SEGMENT__REC_EXP;

  /**
   * The feature id for the '<em><b>Call</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINAL_CALL_EXP_SEGMENT__CALL = NAVIGATION_SEGMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Final Call Exp Segment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINAL_CALL_EXP_SEGMENT_FEATURE_COUNT = NAVIGATION_SEGMENT_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.RRoot <em>RRoot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RRoot</em>'.
   * @see org.eclipse.ecoretools.ale.RRoot
   * @generated
   */
  EClass getRRoot();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.ecoretools.ale.RRoot#getXtendedClasses <em>Xtended Classes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Xtended Classes</em>'.
   * @see org.eclipse.ecoretools.ale.RRoot#getXtendedClasses()
   * @see #getRRoot()
   * @generated
   */
  EReference getRRoot_XtendedClasses();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.RClass <em>RClass</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RClass</em>'.
   * @see org.eclipse.ecoretools.ale.RClass
   * @generated
   */
  EClass getRClass();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.ecoretools.ale.RClass#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.eclipse.ecoretools.ale.RClass#getName()
   * @see #getRClass()
   * @generated
   */
  EAttribute getRClass_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.ecoretools.ale.RClass#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see org.eclipse.ecoretools.ale.RClass#getAttributes()
   * @see #getRClass()
   * @generated
   */
  EReference getRClass_Attributes();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.ecoretools.ale.RClass#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see org.eclipse.ecoretools.ale.RClass#getOperations()
   * @see #getRClass()
   * @generated
   */
  EReference getRClass_Operations();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.ROpenClass <em>ROpen Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ROpen Class</em>'.
   * @see org.eclipse.ecoretools.ale.ROpenClass
   * @generated
   */
  EClass getROpenClass();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.ROpenClass#getOpenClass <em>Open Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Open Class</em>'.
   * @see org.eclipse.ecoretools.ale.ROpenClass#getOpenClass()
   * @see #getROpenClass()
   * @generated
   */
  EReference getROpenClass_OpenClass();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.RNewClass <em>RNew Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RNew Class</em>'.
   * @see org.eclipse.ecoretools.ale.RNewClass
   * @generated
   */
  EClass getRNewClass();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.RNewClass#getNewClass <em>New Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>New Class</em>'.
   * @see org.eclipse.ecoretools.ale.RNewClass#getNewClass()
   * @see #getRNewClass()
   * @generated
   */
  EReference getRNewClass_NewClass();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.rOperation <em>rOperation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>rOperation</em>'.
   * @see org.eclipse.ecoretools.ale.rOperation
   * @generated
   */
  EClass getrOperation();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.ecoretools.ale.rOperation#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.eclipse.ecoretools.ale.rOperation#getType()
   * @see #getrOperation()
   * @generated
   */
  EAttribute getrOperation_Type();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.ecoretools.ale.rOperation#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.eclipse.ecoretools.ale.rOperation#getName()
   * @see #getrOperation()
   * @generated
   */
  EAttribute getrOperation_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.ecoretools.ale.rOperation#getParamList <em>Param List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Param List</em>'.
   * @see org.eclipse.ecoretools.ale.rOperation#getParamList()
   * @see #getrOperation()
   * @generated
   */
  EReference getrOperation_ParamList();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.rOperation#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see org.eclipse.ecoretools.ale.rOperation#getBody()
   * @see #getrOperation()
   * @generated
   */
  EReference getrOperation_Body();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.rParameters <em>rParameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>rParameters</em>'.
   * @see org.eclipse.ecoretools.ale.rParameters
   * @generated
   */
  EClass getrParameters();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.ecoretools.ale.rParameters#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see org.eclipse.ecoretools.ale.rParameters#getParams()
   * @see #getrParameters()
   * @generated
   */
  EReference getrParameters_Params();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.rVariable <em>rVariable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>rVariable</em>'.
   * @see org.eclipse.ecoretools.ale.rVariable
   * @generated
   */
  EClass getrVariable();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.ecoretools.ale.rVariable#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.eclipse.ecoretools.ale.rVariable#getType()
   * @see #getrVariable()
   * @generated
   */
  EAttribute getrVariable_Type();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.ecoretools.ale.rVariable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.eclipse.ecoretools.ale.rVariable#getName()
   * @see #getrVariable()
   * @generated
   */
  EAttribute getrVariable_Name();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.rAttribute <em>rAttribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>rAttribute</em>'.
   * @see org.eclipse.ecoretools.ale.rAttribute
   * @generated
   */
  EClass getrAttribute();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.ecoretools.ale.rAttribute#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.eclipse.ecoretools.ale.rAttribute#getType()
   * @see #getrAttribute()
   * @generated
   */
  EAttribute getrAttribute_Type();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.ecoretools.ale.rAttribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.eclipse.ecoretools.ale.rAttribute#getName()
   * @see #getrAttribute()
   * @generated
   */
  EAttribute getrAttribute_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.rAttribute#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see org.eclipse.ecoretools.ale.rAttribute#getExpr()
   * @see #getrAttribute()
   * @generated
   */
  EReference getrAttribute_Expr();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.RStatement <em>RStatement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RStatement</em>'.
   * @see org.eclipse.ecoretools.ale.RStatement
   * @generated
   */
  EClass getRStatement();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.rVarDecl <em>rVar Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>rVar Decl</em>'.
   * @see org.eclipse.ecoretools.ale.rVarDecl
   * @generated
   */
  EClass getrVarDecl();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.RAssign <em>RAssign</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RAssign</em>'.
   * @see org.eclipse.ecoretools.ale.RAssign
   * @generated
   */
  EClass getRAssign();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.RAssign#getStmt <em>Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Stmt</em>'.
   * @see org.eclipse.ecoretools.ale.RAssign#getStmt()
   * @see #getRAssign()
   * @generated
   */
  EReference getRAssign_Stmt();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.RAssign#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.eclipse.ecoretools.ale.RAssign#getLeft()
   * @see #getRAssign()
   * @generated
   */
  EReference getRAssign_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.RAssign#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.eclipse.ecoretools.ale.RAssign#getRight()
   * @see #getRAssign()
   * @generated
   */
  EReference getRAssign_Right();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.RForEach <em>RFor Each</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RFor Each</em>'.
   * @see org.eclipse.ecoretools.ale.RForEach
   * @generated
   */
  EClass getRForEach();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.RForEach#getForEach <em>For Each</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>For Each</em>'.
   * @see org.eclipse.ecoretools.ale.RForEach#getForEach()
   * @see #getRForEach()
   * @generated
   */
  EReference getRForEach_ForEach();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.rCollection <em>rCollection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>rCollection</em>'.
   * @see org.eclipse.ecoretools.ale.rCollection
   * @generated
   */
  EClass getrCollection();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.rCollection#getBlock <em>Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Block</em>'.
   * @see org.eclipse.ecoretools.ale.rCollection#getBlock()
   * @see #getrCollection()
   * @generated
   */
  EReference getrCollection_Block();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.rBlock <em>rBlock</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>rBlock</em>'.
   * @see org.eclipse.ecoretools.ale.rBlock
   * @generated
   */
  EClass getrBlock();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.ecoretools.ale.rBlock#getStatement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statement</em>'.
   * @see org.eclipse.ecoretools.ale.rBlock#getStatement()
   * @see #getrBlock()
   * @generated
   */
  EReference getrBlock_Statement();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.RIf <em>RIf</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RIf</em>'.
   * @see org.eclipse.ecoretools.ale.RIf
   * @generated
   */
  EClass getRIf();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.RIf#getIf <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>If</em>'.
   * @see org.eclipse.ecoretools.ale.RIf#getIf()
   * @see #getRIf()
   * @generated
   */
  EReference getRIf_If();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.RIf#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see org.eclipse.ecoretools.ale.RIf#getCondition()
   * @see #getRIf()
   * @generated
   */
  EReference getRIf_Condition();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.RIf#getIfBlock <em>If Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>If Block</em>'.
   * @see org.eclipse.ecoretools.ale.RIf#getIfBlock()
   * @see #getRIf()
   * @generated
   */
  EReference getRIf_IfBlock();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.RIf#getElseBlock <em>Else Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Else Block</em>'.
   * @see org.eclipse.ecoretools.ale.RIf#getElseBlock()
   * @see #getRIf()
   * @generated
   */
  EReference getRIf_ElseBlock();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.RWhile <em>RWhile</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RWhile</em>'.
   * @see org.eclipse.ecoretools.ale.RWhile
   * @generated
   */
  EClass getRWhile();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.RWhile#getWhile <em>While</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>While</em>'.
   * @see org.eclipse.ecoretools.ale.RWhile#getWhile()
   * @see #getRWhile()
   * @generated
   */
  EReference getRWhile_While();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.RExpression <em>RExpression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RExpression</em>'.
   * @see org.eclipse.ecoretools.ale.RExpression
   * @generated
   */
  EClass getRExpression();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.RExpression#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see org.eclipse.ecoretools.ale.RExpression#getExpr()
   * @see #getRExpression()
   * @generated
   */
  EReference getRExpression_Expr();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.Expr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr</em>'.
   * @see org.eclipse.ecoretools.ale.Expr
   * @generated
   */
  EClass getExpr();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.Expr#getLeftPart <em>Left Part</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left Part</em>'.
   * @see org.eclipse.ecoretools.ale.Expr#getLeftPart()
   * @see #getExpr()
   * @generated
   */
  EReference getExpr_LeftPart();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.Expr#getRecpart <em>Recpart</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Recpart</em>'.
   * @see org.eclipse.ecoretools.ale.Expr#getRecpart()
   * @see #getExpr()
   * @generated
   */
  EReference getExpr_Recpart();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.RecExpression <em>Rec Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rec Expression</em>'.
   * @see org.eclipse.ecoretools.ale.RecExpression
   * @generated
   */
  EClass getRecExpression();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.RecExpression#getRecExp <em>Rec Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rec Exp</em>'.
   * @see org.eclipse.ecoretools.ale.RecExpression#getRecExp()
   * @see #getRecExpression()
   * @generated
   */
  EReference getRecExpression_RecExp();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.NavigationSegment <em>Navigation Segment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Navigation Segment</em>'.
   * @see org.eclipse.ecoretools.ale.NavigationSegment
   * @generated
   */
  EClass getNavigationSegment();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.nonLeftRecExpression <em>non Left Rec Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>non Left Rec Expression</em>'.
   * @see org.eclipse.ecoretools.ale.nonLeftRecExpression
   * @generated
   */
  EClass getnonLeftRecExpression();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.nonLeftRecExpression#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see org.eclipse.ecoretools.ale.nonLeftRecExpression#getCondition()
   * @see #getnonLeftRecExpression()
   * @generated
   */
  EReference getnonLeftRecExpression_Condition();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.nonLeftRecExpression#getIfBlock <em>If Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>If Block</em>'.
   * @see org.eclipse.ecoretools.ale.nonLeftRecExpression#getIfBlock()
   * @see #getnonLeftRecExpression()
   * @generated
   */
  EReference getnonLeftRecExpression_IfBlock();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.nonLeftRecExpression#getElseBlock <em>Else Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Else Block</em>'.
   * @see org.eclipse.ecoretools.ale.nonLeftRecExpression#getElseBlock()
   * @see #getnonLeftRecExpression()
   * @generated
   */
  EReference getnonLeftRecExpression_ElseBlock();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.ecoretools.ale.nonLeftRecExpression#getBindings <em>Bindings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Bindings</em>'.
   * @see org.eclipse.ecoretools.ale.nonLeftRecExpression#getBindings()
   * @see #getnonLeftRecExpression()
   * @generated
   */
  EReference getnonLeftRecExpression_Bindings();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.nonLeftRecExpression#getLetExpr <em>Let Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Let Expr</em>'.
   * @see org.eclipse.ecoretools.ale.nonLeftRecExpression#getLetExpr()
   * @see #getnonLeftRecExpression()
   * @generated
   */
  EReference getnonLeftRecExpression_LetExpr();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.binding <em>binding</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>binding</em>'.
   * @see org.eclipse.ecoretools.ale.binding
   * @generated
   */
  EClass getbinding();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.callExp <em>call Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>call Exp</em>'.
   * @see org.eclipse.ecoretools.ale.callExp
   * @generated
   */
  EClass getcallExp();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.expressionSequence <em>expression Sequence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>expression Sequence</em>'.
   * @see org.eclipse.ecoretools.ale.expressionSequence
   * @generated
   */
  EClass getexpressionSequence();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.ecoretools.ale.expressionSequence#getSeqExprs <em>Seq Exprs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Seq Exprs</em>'.
   * @see org.eclipse.ecoretools.ale.expressionSequence#getSeqExprs()
   * @see #getexpressionSequence()
   * @generated
   */
  EReference getexpressionSequence_SeqExprs();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.literal <em>literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>literal</em>'.
   * @see org.eclipse.ecoretools.ale.literal
   * @generated
   */
  EClass getliteral();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.RValDecl <em>RVal Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RVal Decl</em>'.
   * @see org.eclipse.ecoretools.ale.RValDecl
   * @generated
   */
  EClass getRValDecl();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.RValDecl#getStmt <em>Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Stmt</em>'.
   * @see org.eclipse.ecoretools.ale.RValDecl#getStmt()
   * @see #getRValDecl()
   * @generated
   */
  EReference getRValDecl_Stmt();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.FinalIdentSegment <em>Final Ident Segment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Final Ident Segment</em>'.
   * @see org.eclipse.ecoretools.ale.FinalIdentSegment
   * @generated
   */
  EClass getFinalIdentSegment();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.ecoretools.ale.FinalIdentSegment#getIdent <em>Ident</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ident</em>'.
   * @see org.eclipse.ecoretools.ale.FinalIdentSegment#getIdent()
   * @see #getFinalIdentSegment()
   * @generated
   */
  EAttribute getFinalIdentSegment_Ident();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.FinalIdentCallSegment <em>Final Ident Call Segment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Final Ident Call Segment</em>'.
   * @see org.eclipse.ecoretools.ale.FinalIdentCallSegment
   * @generated
   */
  EClass getFinalIdentCallSegment();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.FinalIdentCallSegment#getCall <em>Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Call</em>'.
   * @see org.eclipse.ecoretools.ale.FinalIdentCallSegment#getCall()
   * @see #getFinalIdentCallSegment()
   * @generated
   */
  EReference getFinalIdentCallSegment_Call();

  /**
   * Returns the meta object for class '{@link org.eclipse.ecoretools.ale.FinalCallExpSegment <em>Final Call Exp Segment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Final Call Exp Segment</em>'.
   * @see org.eclipse.ecoretools.ale.FinalCallExpSegment
   * @generated
   */
  EClass getFinalCallExpSegment();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.ecoretools.ale.FinalCallExpSegment#getCall <em>Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Call</em>'.
   * @see org.eclipse.ecoretools.ale.FinalCallExpSegment#getCall()
   * @see #getFinalCallExpSegment()
   * @generated
   */
  EReference getFinalCallExpSegment_Call();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AleFactory getAleFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.RRootImpl <em>RRoot</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.RRootImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRRoot()
     * @generated
     */
    EClass RROOT = eINSTANCE.getRRoot();

    /**
     * The meta object literal for the '<em><b>Xtended Classes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RROOT__XTENDED_CLASSES = eINSTANCE.getRRoot_XtendedClasses();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.RClassImpl <em>RClass</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.RClassImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRClass()
     * @generated
     */
    EClass RCLASS = eINSTANCE.getRClass();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RCLASS__NAME = eINSTANCE.getRClass_Name();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RCLASS__ATTRIBUTES = eINSTANCE.getRClass_Attributes();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RCLASS__OPERATIONS = eINSTANCE.getRClass_Operations();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.ROpenClassImpl <em>ROpen Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.ROpenClassImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getROpenClass()
     * @generated
     */
    EClass ROPEN_CLASS = eINSTANCE.getROpenClass();

    /**
     * The meta object literal for the '<em><b>Open Class</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROPEN_CLASS__OPEN_CLASS = eINSTANCE.getROpenClass_OpenClass();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.RNewClassImpl <em>RNew Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.RNewClassImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRNewClass()
     * @generated
     */
    EClass RNEW_CLASS = eINSTANCE.getRNewClass();

    /**
     * The meta object literal for the '<em><b>New Class</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RNEW_CLASS__NEW_CLASS = eINSTANCE.getRNewClass_NewClass();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.rOperationImpl <em>rOperation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.rOperationImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getrOperation()
     * @generated
     */
    EClass ROPERATION = eINSTANCE.getrOperation();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROPERATION__TYPE = eINSTANCE.getrOperation_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROPERATION__NAME = eINSTANCE.getrOperation_Name();

    /**
     * The meta object literal for the '<em><b>Param List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROPERATION__PARAM_LIST = eINSTANCE.getrOperation_ParamList();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROPERATION__BODY = eINSTANCE.getrOperation_Body();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.rParametersImpl <em>rParameters</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.rParametersImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getrParameters()
     * @generated
     */
    EClass RPARAMETERS = eINSTANCE.getrParameters();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RPARAMETERS__PARAMS = eINSTANCE.getrParameters_Params();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.rVariableImpl <em>rVariable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.rVariableImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getrVariable()
     * @generated
     */
    EClass RVARIABLE = eINSTANCE.getrVariable();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RVARIABLE__TYPE = eINSTANCE.getrVariable_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RVARIABLE__NAME = eINSTANCE.getrVariable_Name();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.rAttributeImpl <em>rAttribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.rAttributeImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getrAttribute()
     * @generated
     */
    EClass RATTRIBUTE = eINSTANCE.getrAttribute();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RATTRIBUTE__TYPE = eINSTANCE.getrAttribute_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RATTRIBUTE__NAME = eINSTANCE.getrAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RATTRIBUTE__EXPR = eINSTANCE.getrAttribute_Expr();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.RStatementImpl <em>RStatement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.RStatementImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRStatement()
     * @generated
     */
    EClass RSTATEMENT = eINSTANCE.getRStatement();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.rVarDeclImpl <em>rVar Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.rVarDeclImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getrVarDecl()
     * @generated
     */
    EClass RVAR_DECL = eINSTANCE.getrVarDecl();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.RAssignImpl <em>RAssign</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.RAssignImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRAssign()
     * @generated
     */
    EClass RASSIGN = eINSTANCE.getRAssign();

    /**
     * The meta object literal for the '<em><b>Stmt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RASSIGN__STMT = eINSTANCE.getRAssign_Stmt();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RASSIGN__LEFT = eINSTANCE.getRAssign_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RASSIGN__RIGHT = eINSTANCE.getRAssign_Right();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.RForEachImpl <em>RFor Each</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.RForEachImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRForEach()
     * @generated
     */
    EClass RFOR_EACH = eINSTANCE.getRForEach();

    /**
     * The meta object literal for the '<em><b>For Each</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RFOR_EACH__FOR_EACH = eINSTANCE.getRForEach_ForEach();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.rCollectionImpl <em>rCollection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.rCollectionImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getrCollection()
     * @generated
     */
    EClass RCOLLECTION = eINSTANCE.getrCollection();

    /**
     * The meta object literal for the '<em><b>Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RCOLLECTION__BLOCK = eINSTANCE.getrCollection_Block();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.rBlockImpl <em>rBlock</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.rBlockImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getrBlock()
     * @generated
     */
    EClass RBLOCK = eINSTANCE.getrBlock();

    /**
     * The meta object literal for the '<em><b>Statement</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RBLOCK__STATEMENT = eINSTANCE.getrBlock_Statement();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.RIfImpl <em>RIf</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.RIfImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRIf()
     * @generated
     */
    EClass RIF = eINSTANCE.getRIf();

    /**
     * The meta object literal for the '<em><b>If</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RIF__IF = eINSTANCE.getRIf_If();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RIF__CONDITION = eINSTANCE.getRIf_Condition();

    /**
     * The meta object literal for the '<em><b>If Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RIF__IF_BLOCK = eINSTANCE.getRIf_IfBlock();

    /**
     * The meta object literal for the '<em><b>Else Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RIF__ELSE_BLOCK = eINSTANCE.getRIf_ElseBlock();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.RWhileImpl <em>RWhile</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.RWhileImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRWhile()
     * @generated
     */
    EClass RWHILE = eINSTANCE.getRWhile();

    /**
     * The meta object literal for the '<em><b>While</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RWHILE__WHILE = eINSTANCE.getRWhile_While();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.RExpressionImpl <em>RExpression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.RExpressionImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRExpression()
     * @generated
     */
    EClass REXPRESSION = eINSTANCE.getRExpression();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REXPRESSION__EXPR = eINSTANCE.getRExpression_Expr();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.ExprImpl <em>Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.ExprImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getExpr()
     * @generated
     */
    EClass EXPR = eINSTANCE.getExpr();

    /**
     * The meta object literal for the '<em><b>Left Part</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR__LEFT_PART = eINSTANCE.getExpr_LeftPart();

    /**
     * The meta object literal for the '<em><b>Recpart</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR__RECPART = eINSTANCE.getExpr_Recpart();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.RecExpressionImpl <em>Rec Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.RecExpressionImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRecExpression()
     * @generated
     */
    EClass REC_EXPRESSION = eINSTANCE.getRecExpression();

    /**
     * The meta object literal for the '<em><b>Rec Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REC_EXPRESSION__REC_EXP = eINSTANCE.getRecExpression_RecExp();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.NavigationSegmentImpl <em>Navigation Segment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.NavigationSegmentImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getNavigationSegment()
     * @generated
     */
    EClass NAVIGATION_SEGMENT = eINSTANCE.getNavigationSegment();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.nonLeftRecExpressionImpl <em>non Left Rec Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.nonLeftRecExpressionImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getnonLeftRecExpression()
     * @generated
     */
    EClass NON_LEFT_REC_EXPRESSION = eINSTANCE.getnonLeftRecExpression();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NON_LEFT_REC_EXPRESSION__CONDITION = eINSTANCE.getnonLeftRecExpression_Condition();

    /**
     * The meta object literal for the '<em><b>If Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NON_LEFT_REC_EXPRESSION__IF_BLOCK = eINSTANCE.getnonLeftRecExpression_IfBlock();

    /**
     * The meta object literal for the '<em><b>Else Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NON_LEFT_REC_EXPRESSION__ELSE_BLOCK = eINSTANCE.getnonLeftRecExpression_ElseBlock();

    /**
     * The meta object literal for the '<em><b>Bindings</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NON_LEFT_REC_EXPRESSION__BINDINGS = eINSTANCE.getnonLeftRecExpression_Bindings();

    /**
     * The meta object literal for the '<em><b>Let Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NON_LEFT_REC_EXPRESSION__LET_EXPR = eINSTANCE.getnonLeftRecExpression_LetExpr();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.bindingImpl <em>binding</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.bindingImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getbinding()
     * @generated
     */
    EClass BINDING = eINSTANCE.getbinding();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.callExpImpl <em>call Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.callExpImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getcallExp()
     * @generated
     */
    EClass CALL_EXP = eINSTANCE.getcallExp();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.expressionSequenceImpl <em>expression Sequence</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.expressionSequenceImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getexpressionSequence()
     * @generated
     */
    EClass EXPRESSION_SEQUENCE = eINSTANCE.getexpressionSequence();

    /**
     * The meta object literal for the '<em><b>Seq Exprs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_SEQUENCE__SEQ_EXPRS = eINSTANCE.getexpressionSequence_SeqExprs();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.literalImpl <em>literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.literalImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getliteral()
     * @generated
     */
    EClass LITERAL = eINSTANCE.getliteral();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.RValDeclImpl <em>RVal Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.RValDeclImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getRValDecl()
     * @generated
     */
    EClass RVAL_DECL = eINSTANCE.getRValDecl();

    /**
     * The meta object literal for the '<em><b>Stmt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RVAL_DECL__STMT = eINSTANCE.getRValDecl_Stmt();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.FinalIdentSegmentImpl <em>Final Ident Segment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.FinalIdentSegmentImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getFinalIdentSegment()
     * @generated
     */
    EClass FINAL_IDENT_SEGMENT = eINSTANCE.getFinalIdentSegment();

    /**
     * The meta object literal for the '<em><b>Ident</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FINAL_IDENT_SEGMENT__IDENT = eINSTANCE.getFinalIdentSegment_Ident();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.FinalIdentCallSegmentImpl <em>Final Ident Call Segment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.FinalIdentCallSegmentImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getFinalIdentCallSegment()
     * @generated
     */
    EClass FINAL_IDENT_CALL_SEGMENT = eINSTANCE.getFinalIdentCallSegment();

    /**
     * The meta object literal for the '<em><b>Call</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FINAL_IDENT_CALL_SEGMENT__CALL = eINSTANCE.getFinalIdentCallSegment_Call();

    /**
     * The meta object literal for the '{@link org.eclipse.ecoretools.ale.impl.FinalCallExpSegmentImpl <em>Final Call Exp Segment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.ecoretools.ale.impl.FinalCallExpSegmentImpl
     * @see org.eclipse.ecoretools.ale.impl.AlePackageImpl#getFinalCallExpSegment()
     * @generated
     */
    EClass FINAL_CALL_EXP_SEGMENT = eINSTANCE.getFinalCallExpSegment();

    /**
     * The meta object literal for the '<em><b>Call</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FINAL_CALL_EXP_SEGMENT__CALL = eINSTANCE.getFinalCallExpSegment_Call();

  }

} //AlePackage
