/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.ecoretools.ale;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Let Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.ecoretools.ale.LetExpression#getBindings <em>Bindings</em>}</li>
 *   <li>{@link org.eclipse.ecoretools.ale.LetExpression#getLetExpr <em>Let Expr</em>}</li>
 * </ul>
 *
 * @see org.eclipse.ecoretools.ale.AlePackage#getLetExpression()
 * @model
 * @generated
 */
public interface LetExpression extends Expr
{
  /**
   * Returns the value of the '<em><b>Bindings</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.ecoretools.ale.Binding}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bindings</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bindings</em>' containment reference list.
   * @see org.eclipse.ecoretools.ale.AlePackage#getLetExpression_Bindings()
   * @model containment="true"
   * @generated
   */
  EList<Binding> getBindings();

  /**
   * Returns the value of the '<em><b>Let Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Let Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Let Expr</em>' containment reference.
   * @see #setLetExpr(Expr)
   * @see org.eclipse.ecoretools.ale.AlePackage#getLetExpression_LetExpr()
   * @model containment="true"
   * @generated
   */
  Expr getLetExpr();

  /**
   * Sets the value of the '{@link org.eclipse.ecoretools.ale.LetExpression#getLetExpr <em>Let Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Let Expr</em>' containment reference.
   * @see #getLetExpr()
   * @generated
   */
  void setLetExpr(Expr value);

} // LetExpression
