/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.ecoretools.ale;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>RRoot</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.ecoretools.ale.RRoot#getXtendedClasses <em>Xtended Classes</em>}</li>
 * </ul>
 *
 * @see org.eclipse.ecoretools.ale.AlePackage#getRRoot()
 * @model
 * @generated
 */
public interface RRoot extends EObject
{
  /**
   * Returns the value of the '<em><b>Xtended Classes</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.ecoretools.ale.RClass}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Xtended Classes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Xtended Classes</em>' containment reference list.
   * @see org.eclipse.ecoretools.ale.AlePackage#getRRoot_XtendedClasses()
   * @model containment="true"
   * @generated
   */
  EList<RClass> getXtendedClasses();

} // RRoot
