/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.ecoretools.ale;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>RType</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.ecoretools.ale.AlePackage#getRType()
 * @model
 * @generated
 */
public interface RType extends EObject
{
} // RType
