/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.ecoretools.ale;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Literal String</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.ecoretools.ale.AlePackage#getTypeLiteralString()
 * @model
 * @generated
 */
public interface TypeLiteralString extends TypeLiteral
{
} // TypeLiteralString
