/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>RNew Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.RNewClass#getNewClass <em>New Class</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRNewClass()
 * @model
 * @generated
 */
public interface RNewClass extends RClass
{
  /**
   * Returns the value of the '<em><b>New Class</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>New Class</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>New Class</em>' containment reference.
   * @see #setNewClass(RNewClass)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRNewClass_NewClass()
   * @model containment="true"
   * @generated
   */
  RNewClass getNewClass();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.RNewClass#getNewClass <em>New Class</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>New Class</em>' containment reference.
   * @see #getNewClass()
   * @generated
   */
  void setNewClass(RNewClass value);

} // RNewClass
