/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>RWhile</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.RWhile#getWhile <em>While</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRWhile()
 * @model
 * @generated
 */
public interface RWhile extends RStatement
{
  /**
   * Returns the value of the '<em><b>While</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>While</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>While</em>' containment reference.
   * @see #setWhile(RWhile)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRWhile_While()
   * @model containment="true"
   * @generated
   */
  RWhile getWhile();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.RWhile#getWhile <em>While</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>While</em>' containment reference.
   * @see #getWhile()
   * @generated
   */
  void setWhile(RWhile value);

} // RWhile
